# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    #ENV["VERSION"] = get_version_number(target: "Moop")
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    cocoapods(repo_update: true)
  end

  lane :archive do |options|
    # Clear output directory
    sh "rm -rf #{Dir.pwd}/output"

    build_app(scheme: "Moop",
              configuration: "AppStore",
              clean: true,
              workspace: "Moop.xcworkspace",
              output_directory: "#{Dir.pwd}/output",
              include_bitcode: true)
    notification(subtitle: "Finished Building", message: "Ready to upload...")
  end

  desc "Description of what the lane does"
  lane :beta do
    archive()
    upload_to_testflight(
      username: "scw422@hanmail.net",
      app_identifier: "com.kor45cw.Moop",
      ipa: "#{Dir.pwd}/output/Moop.ipa",
      skip_waiting_for_build_processing: true)
  end

  lane :upload_appstore do
    archive()
    upload_to_app_store(
      username: "scw422@hanmail.net",
      app_identifier: "com.kor45cw.Moop",
      app: 1464896856,
      ipa: "#{Dir.pwd}/output/Moop.ipa",
      submit_for_review: true,
      automatic_release: true,
      skip_screenshots: true,
      force: true)
  end

  lane :travis do 
    # Fetch the keychain env variables
    # securely stored in the travis.yml.
    keychain_name = ENV["MATCH_KEYCHAIN_NAME"]
    keychain_password = ENV["MATCH_KEYCHAIN_PASSWORD"]
    match_git_url = ENV["MATCH_GIT_URL"]

    # Create a temporary keychain to 
    # store the certificates.
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    # Fetch the necessary certificates and 
    # provisioning profiles.
    match(
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      git_url: match_git_url,
      type: "appstore",
      readonly: true
    )

    archive()

    upload_to_testflight(
      username: "scw422@hanmail.net",
      app_identifier: "com.kor45cw.Moop",
      ipa: "#{Dir.pwd}/output/Moop.ipa",
      skip_waiting_for_build_processing: true)

    delete_keychain(
      name: keychain_name
    )
  end

  lane :refresh_dsyms do
    download_dsyms(
      min_version: "3.1.0",
      username: "scw422@hanmail.net",
      app_identifier: "com.kor45cw.Moop",
      output_directory: "#{Dir.pwd}/output/dSYM")                # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  after_all do |lane, options|
    slack(message: "Fastlane finish!",
          slack_url: "https://hooks.slack.com/services/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")
  end

end
